---
abstract: 'Perl interface to the GMP integer functions'
author:
  - 'Sisyphus (sisyphus at (@) cpan dot (.) org)'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-GMPz
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/sisyphus/math-gmpz.git
version: 0.39
